config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get "cart", to: "cart_items#index"
  delete "cart/reset", to: "cart_items#reset"

  resources :cart_items, only: [:destroy] do
    collection do
      post :upsert
    end
  end

  resources :products

  root "products#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

  class << self
    def find_with_response(id, includes: nil)
      find_wrapper(id, includes) { includes(includes).find(id) }
    end

    def find_wrapper(id, _includes)
      Response.success(yield)
    rescue ActiveRecord::RecordNotFound => _e
      Response.failure("Cannot find #{name} with id: #{id}")
    end
  end

  def save_with_response(**args)
    assign_attributes(args)
    if save
      Response.success(self)
    else
      Response.failure(errors.full_messages.to_sentence)
    end
  end

  def update_attributes_with_response(args)
    if errors.details.empty? && update(args)
      Response.success(self)
    else
      Response.failure(errors.full_messages.to_sentence)
    end
  end

  def destroy_with_response
    if destroy
      Response.success(self)
    else
      Response.failure(errors.full_messages.to_sentence)
    end
  end

  private

  def response_success
    Response.success(self)
  end

  def response_failure
    Response.failure(errors.full_messages.to_sentence)
  end
end

app/models/cart.rb
# frozen_string_literal: true

class Cart < ApplicationRecord
  has_many :cart_items, dependent: :delete_all
  has_many :products, through: :cart_items
end

app/models/cart_item.rb
# frozen_string_literal: true

class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product

  with_options presence: true do
    validates :quantity, numericality: { greater_than: 0 }
    validates :total_price
  end
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  has_many :cart_items, dependent: :delete_all
  has_one_attached :image

  with_options presence: true do
    validates :name, :vendor, :price
    validates :price, numericality: { greater_than: 0 }
    validates :price_in_dollars, numericality: { greater_than: 0 }
  end

  before_validation :convert_price_to_cents
  after_update_commit :update_cart_items_price

  def product_image
    return unless persisted? && image.attached?

    Rails.application.routes.url_helpers.rails_representation_url(
      image.variant(resize_to_fit: [150, 250], format: :webp),
      only_path: true
    )
  end

  def price_in_dollars
    price.present? ? price.to_d / 100 : nil
  end

  def price_in_dollars=(dollar_amount)
    self.price = (dollar_amount.to_d * 100).round(0) if dollar_amount.present?
  end

  private

  def convert_price_to_cents
    return if price.present? && price > 100

    self.price = (price_in_dollars.to_d * 100).round(0) if price_in_dollars.present?
  end

  def update_cart_items_price
    cart_items.each { _1.update(total_price: price * _1.quantity) }
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :initialize_cart

  private

  def initialize_cart
    @cart ||= Cart.find_by(id: session[:cart_id]) || Cart.create
    session[:cart_id] = @cart.id
  end
end

app/controllers/cart_items_controller.rb
# frozen_string_literal: true

class CartItemsController < ApplicationController
  include ApplicationHelper

  def index
    @cart_items = CartItem.eager_load(:product).where(cart_id: @cart.id).order(created_at: :asc)
  end

  def upsert # rubocop:disable Metrics/AbcSize
    response = ShoppingCart::CartItems::Upsert.new(cart: @cart, product_id: params[:product_id],
                                                   quantity: params[:quantity],
                                                   operation: params[:operation]).call

    if response.success?
      @cart_item = response.value
      respond_to do |format|
        format.turbo_stream
        format.html { redirect_to cart_items_path, notice: "Your cart has been updated!" }
      end
    else
      render turbo_stream: turbo_toast(message: response.value, type: "danger"),
             status: :unprocessable_entity
    end
  end

  def destroy # rubocop:disable Metrics/AbcSize
    response = ShoppingCart::CartItems::Destroy.new(cart: @cart, cart_item_id: params[:id]).call

    if response.success?
      @cart_item_id = params[:id]
      respond_to do |format|
        format.turbo_stream
        format.html do
          redirect_to cart_items_path, notice: "The product has been removed from your cart!"
        end
      end
    else
      render turbo_stream: turbo_toast(message: response.value, type: "danger"),
             status: :unprocessable_entity
    end
  end

  def reset
    response = ShoppingCart::Reset.new(cart: @cart).call

    if response.success?
      respond_to do |format|
        format.turbo_stream
        format.html { redirect_to cart_items_path, notice: "Your cart has been emptied!" }
      end
    else
      render turbo_stream: turbo_toast(message: response.value, type: "error"),
             status: :unprocessable_entity
    end
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  before_action :product, only: [:edit, :destroy]

  def index
    @products = Product.order(created_at: :desc)
  end

  def new
    @product = Product.new
  end

  def edit
    respond_to do |format|
      format.turbo_stream
      format.html
    end
  end

  def create # rubocop:disable Metrics/AbcSize
    @product = Product.find_or_initialize_by(product_attributes.except(:image, :price_in_dollars))
    %i(price_in_dollars image).each do |attribute|
      next if product_attributes[attribute].nil?

      @product.public_send("#{attribute}=", product_attributes[attribute])
    end

    respond_to do |format|
      if @product.save
        format.turbo_stream
        format.html { redirect_to products_path }
      else
        format.turbo_stream { render :create_failure }
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if product.update(product_attributes)
        format.turbo_stream
        format.html do
          redirect_to products_path, notice: "The product has been updated successfully!"
        end
      else
        format.turbo_stream { render :update_failure }
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product.destroy
    products = Product.all

    respond_to do |format|
      if products.any?
        format.turbo_stream
      else
        format.turbo_stream { render :destroy_empty_state }
      end
      format.html { redirect_to products_path, notice: "The product was successfully removed!" }
    end
  end

  private

  def product
    @product ||= Product.find(params[:id])
  end

  def product_attributes
    params.expect(product: [:name, :vendor, :price_in_dollars, :image])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def cents_to_amount(amount)
    return if amount.nil?

    format("%.2f", amount.to_d / 100)
  end

  def turbo_toast(type:, message:)
    turbo_stream.append("toast-container", partial: "shared/toast", locals: { type:, message: })
  end
end

app/views/cart_items/_cart_item.html.erb
<div id="cart_item_<%= cart_item.id %>" class="mb-3">
  <div class="row align-items-center mb-2">
    <div class="col-12 col-md-2 text-center mb-2 mb-md-0">
      <%= image_tag cart_item.product.product_image, class: "img-fluid rounded", loading: "lazy" if cart_item.product.image.attached? %>
    </div>
    <div class="col-12 col-md-4 h-100 text-center justify-xs-center text-md-start d-flex align-items-center">
      <p class="mb-0"><%= "#{cart_item.product.name}, #{cart_item.product.vendor}" %></p>
    </div>
    <div class="col-12 col-md-4 text-center text-md-start mt-2 mt-sm-0">
      <%= render partial: "cart_items/quantity", locals: { cart_item: cart_item } %>
    </div>
    <div class="col-12 col-md-2 d-flex flex-column align-items-center align-items-md-end mt-2 mt-sm-0">
      <%= button_to cart_item_path(cart_item), method: :delete, data: { turbo_stream: true, turbo_confirm: "Are you sure you want to remove this item from your cart?" }, class: "btn btn-light" do %>
        <%= fa_icon "trash" %>
      <% end %>
      <p><%= number_to_currency cents_to_amount(cart_item.product.price), unit: "$" %></p>
    </div>
  </div>
  <hr class="text-secondary w-100 mt-2" />
</div>

app/views/cart_items/_empty_state.html.erb
<div class="text-center py-5" id="cart">
  <%= image_tag "box-icon.png", width: 100, height: 100, alt: "Empty Cart", class: "mb-4" %>
  <h2>The cart is empty</h2>
  <p>Add items from <a href="/products">the catalog</a></p>
</div>

app/views/cart_items/_quantity.html.erb
<div data-controller="quantity"
     data-quantity-cart-item-id-value="<%= cart_item.id %>"
     data-quantity-product-id-value="<%= cart_item.product_id %>"
     data-quantity-quantity-value="<%= cart_item.quantity %>"
     class="flex items-center">

  <button type="button" class="btn btn-light" data-action="click->quantity#decrease" aria-label="decrease">
    <i class="fa fa-minus"></i>
  </button>

  <span class="mx-3 fw-bold" data-quantity-target="display">
    <%= cart_item.quantity %>
  </span>

  <button type="button" class="btn btn-light" data-action="click->quantity#increase" aria-label="increase">
    <i class="fa fa-plus"></i>
  </button>
</div>

app/views/cart_items/_totals.html.erb
<% total_price = cart_items.sum { |item| item.quantity * item.product.price } %>
<% total_items = cart_items.sum(&:quantity) %>

<div id="cart_totals" data-controller="totals" data-totals-total-value="<%= total_price %>" data-totals-discount-value="2500">
  <div class="p-3 mb-3 p-2 border rounded">
    <div class="row mb-3">
      <div class="col-8">
        <%= total_items == 1 ? "1 item" : "#{total_items} items" %>
      </div>
      <div class="col-4 d-flex justify-content-end">
        <span data-totals-target="price"><%= number_to_currency cents_to_amount(total_price) %></span>
      </div>
    </div>

    <div class="row mb-4">
      <div class="col-8">
        <span>Move the slider to specify the discount amount</span>
      </div>
      <div class="col-4 d-flex justify-content-end">
        <span class="text-success" data-totals-target="discount">
          <%= number_to_currency cents_to_amount(2500) %>
        </span>
      </div>
    </div>

    <div class="row">
      <div class="col-12">
        <input type="range" class="form-range" min="0" max="10000" step="100" value="2500" data-action="input->totals#update" />
      </div>
    </div>

    <hr />

    <div class="row">
      <div class="col-8 d-flex align-items-center">
        <h5>Total</h5>
      </div>
      <div class="col-4 d-flex align-items-center justify-content-end">
        <h3 data-totals-target="final">
          <%= number_to_currency cents_to_amount(total_price - 2500) %>
        </h3>
      </div>
    </div>
  </div>
</div>

app/views/cart_items/destroy.turbo_stream.erb
<%= turbo_stream.remove "cart_item_#{@cart_item_id}" %>
<%= turbo_stream.replace "cart_totals", partial: "cart_items/totals", locals: { cart_items: @cart.cart_items.includes(:product) } %>
<%= turbo_stream.replace("cart", partial: "cart_items/empty_state") if @cart.reload.cart_items.empty? %>
<%= turbo_toast(message: "The product has been removed from your cart!", type: "success") %>

app/views/cart_items/index.html.erb
<div class="container w-75 position-relative" id="cart">
  <div class="row mb-5">
    <div class="col-6">
      <h2 class="text-2xl font-bold">Cart</h2>
    </div>

    <% if @cart_items.any? %>
      <div class="col-6 d-flex justify-content-end align-items-center">
        <%= button_to "Reset", cart_reset_path,
              method: :delete,
              form: { data: { turbo_stream: true } },
              data: { confirm: "Are you sure you want to empty your cart?" },
              class: "btn btn-light" %>
      </div>
    <% end %>
  </div>

  <% if @cart_items.any? %>
    <% @cart_items.each do |cart_item| %>
      <%= render partial: "cart_item", locals: { cart_item: cart_item } %>
    <% end %>

    <%= render partial: "totals", locals: { cart_items: @cart_items } %>

    <div class="row mb-5">
      <%= button_to "Checkout", cart_reset_path,
            class: "btn btn-success w-100",
            method: :delete,
            form: { data: { turbo_stream: true } } %>
    </div>
  <% else %>
    <%= render partial: "empty_state" %>
  <% end %>
</div>

app/views/cart_items/reset.turbo_stream.erb
<%= turbo_stream.replace "cart", partial: "cart_items/empty_state" %>
<%= turbo_toast(message: "Your cart has been emptied!", type: "success") %>

app/views/cart_items/upsert.turbo_stream.erb
<%= turbo_stream.replace "cart_item_#{@cart_item.id}", partial: "cart_items/cart_item", locals: { cart_item: @cart_item } %>
<%= turbo_stream.replace "cart_totals", partial: "cart_items/totals", locals: { cart_items: @cart.cart_items.includes(:product) } %>
<%= turbo_toast(message: "Your cart has been updated!", type: "success") %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShoppingCart Hotwire</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application" %>
    <%= javascript_pack_tag "application" %>
  </head>

  <body>
    <div class="container-fluid align-items-center">
      <div id="toast-container" class="position-fixed top-0 end-0 p-3" style="z-index: 1050;"></div>
      <div class="row">
        <div class="col-6 mt-3">
          <%= link_to products_path do %>
            <%= image_tag "loadar.png", width: 200 %>
          <% end %>
        </div>
      </div>
      <hr>
      <%= yield %>
      <div id="loader-overlay" class="loader-overlay d-none" data-controller="loader">
        <div class="loader"></div>
      </div>
    </div>
  </body>
</html>

app/views/products/_empty_state.html.erb
<div class="text-center">
  <strong>There are no products in the catalog. Add some!</strong>
</div>

app/views/products/_form.html.erb
<%= turbo_frame_tag product.new_record? ? "new_product" : dom_id(product) do %>
  <%= form_with model: product, data: { turbo_frame: "products" }, class: "needs-validation" do |form| %>
    <div class="row align-items-center mb-3">
      <div class="col-12 col-md-2 text-center mb-2 mb-md-0" data-controller="image-preview">
          <%= form.file_field :image, class: "form-control", accept: "image/*", data: { image_preview_target: "input" } %>
          <img
            id="image-preview"
            src="<%= product.product_image %>"
            class="img-fluid rounded mt-2"
            style="max-width: 100%; height: auto; display: <%= product.image.attached? ? 'block' : 'none' %>;"
            data-image-preview-target="preview"
            data-preview-url=""
          />
      </div>

      <div class="col-12 col-md-4 d-flex flex-column flex-md-row align-items-center justify-content-center justify-content-md-start gap-2">
        <%= render "shared/text_field", form: form, name: :name, type: "text", errors: product.errors[:name] %>
        <%= render "shared/text_field", form: form, name: :vendor, type: "text", errors: product.errors[:vendor] %>
      </div>

      <div class="col-12 col-md-2 d-flex justify-content-center justify-content-md-start mt-2 mt-md-0">
        <%= render "shared/text_field", form: form, name: :price, type: "text", errors: product.errors[:price] %>
      </div>

      <div class="col-12 col-md-4 d-flex justify-content-center justify-content-md-end gap-2 mt-2 mt-md-0">
        <%= form.submit "Save", class: "btn btn-success btn-sm" %>
        <%= link_to "Cancel", products_path, class: "btn btn-light btn-sm" %>
      </div>

      <hr class="text-secondary w-100 mt-2" />
    </div>
  <% end %>
<% end %>

app/views/products/_product.html.erb
<turbo-frame id="product_<%= product.id %>" data-controller="products">
  <div class="row align-items-center">
    <div class="col-12 col-md-2 text-center mb-2 mb-md-0">
      <% if product.image.attached? %>
        <%= image_tag product.image.variant(resize_to_fit: [150, 250]), loading: "lazy", data: { action: "load->product#imageLoaded", turbo_frame: "_top" } %>
      <% end %>
    </div>

    <div class="col-12 col-md-4 h-100 justify-xs-center text-center text-md-start d-flex align-items-center">
      <p class='mb-0'><%= "#{product.name}, #{product.vendor}" %></p>
    </div>

    <div class="col-12 col-md-2 d-flex flex-column align-items-center items-center mt-md-0">
      <p class="text-lg fw-bold mt-3"><%= number_to_currency cents_to_amount(product.price), unit: "$" %></p>
    </div>

    <div class="col-12 col-md-4 text-center d-flex justify-content-end gap-2">
      <%= button_to "Add to cart", upsert_cart_items_path, method: :post, params: { product_id: product.id, quantity: 1, operation: "increment" }, class: "btn btn-light" %>
      <%= link_to edit_product_path(product.id), class: "btn btn-sm btn-light ml-1", title: "Edit product", data: { turbo_frame: "product_#{product.id}" } do %>
        <%= fa_icon "pencil" %>
      <% end %>
      <%= link_to product, class: "btn btn-sm btn-light ml-1", title: "Remove product", data: { confirm: "Do you really want to remove this product?" }, method: :delete do %>
        <%= fa_icon "trash" %>
      <% end %>
    </div>

    <hr class="text-secondary w-100 mt-2" />
  </div>
</turbo-frame>

app/views/products/create.turbo_stream.erb
<%= turbo_stream.prepend("products", partial: "products/product", locals: { product: @product }) %>
<%= turbo_stream.replace("new_product", "") %>
<%= turbo_toast(message: "The product has been created successfully!", type: "success") %>

app/views/products/create_failure.turbo_stream.erb
<%= turbo_stream.replace("new_product", partial: "products/form", locals: { product: @product }) %>

app/views/products/destroy.turbo_stream.erb
<turbo-stream action="remove" target="product_<%= @product.id %>"></turbo-stream>

app/views/products/destroy_empty_state.turbo_stream.erb
<%= turbo_stream.remove(@product) %>
<%= turbo_stream.replace("products", partial: "products/empty_state") %>
<%= turbo_toast(message: "The product was successfully removed!", type: "success") %>

app/views/products/edit.html.erb
<%= render "form", product: @product %>

app/views/products/edit.turbo_stream.erb
<%= turbo_stream.replace("product_#{@product.id}", partial: "products/form", locals: { product: @product }) %>

app/views/products/index.html.erb
<div class="container w-75 position-relative">
  <div class="row mb-5">
    <div class="col-6">
        <h2 class="text-2xl font-bold">Products</h2>
    </div>
    <div class="col-6 d-flex justify-content-end align-items-center gap-2">
        <%= link_to cart_path, class: "btn btn-light", title: "Go to your cart" do %>
          <i class="fa fa-shopping-cart"></i>
        <% end %>
        <%= link_to new_product_path, data: { turbo_frame: "new_product" }, class: "btn btn-success", title: "Add a new product" do %>
          <i class="fa fa-plus"></i>
        <% end %>
    </div>
  </div>

  <%= turbo_frame_tag "products" do %>
    <div class="container">

      <%= turbo_frame_tag "new_product" %>

      <% if @products.any? %>
        <% @products.each do |product| %>
          <%= render product %>
        <% end %>
      <% else %>
        <%= render partial: "products/empty_state" %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/products/new.html.erb
<%= render "form", product: @product %>

app/views/products/update.turbo_stream.erb
<%= turbo_stream.replace("product_#{@product.id}", partial: "products/product", locals: { product: @product }) %>
<%= turbo_toast(message: "The product has been updated successfully!", type: "success") %>

app/views/products/update_failure.turbo_stream.erb
<%= turbo_stream.replace("product_#{@product.id}", partial: "products/form", locals: { product: @product }) %>

app/views/shared/_text_field.html.erb
<div class="mb-3" data-controller="field-errors">
  <%= form.label name, class: "form-label" %>

  <% if name.to_s.include?("price") %>
    <%= form.text_field :price_in_dollars,
        class: "form-control",
        value: form.object.send(name) ? cents_to_amount(form.object.send(name)) : nil,
        placeholder: "Price in dollars",
        data: { field_errors_target: "input" } %>
  <% else %>
    <%= form.text_field name,
        class: "form-control",
        placeholder: name,
        data: { field_errors_target: "input" } %>
  <% end %>

  <% if errors.any? %>
    <p style="color: red" data-field-errors-target="error"><%= errors.join(", ") %></p>
  <% end %>
</div>

app/views/shared/_toast.html.erb
<div class="toast align-items-center text-white mb-2 bg-<%= type %> border-0 show" role="alert" aria-live="assertive" aria-atomic="true" data-controller="toast">
  <div class="d-flex">
    <div class="toast-body">
      <%= message %>
    </div>
    <button type="button" class="btn-close btn-close-white me-2 m-auto" data-action="click->toast#hide"></button>
  </div>
</div>